image: "jjanzic/docker-python3-opencv"

stages:
  - build
  - run
  - test-percentage

build_project:
  stage: build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y   # For opencv
    - pip install opencv-python
#    - pip install --upgrade pip         # If you want to add more requirements, uncomment these 2 lines
#    - pip install -r requirements.txt   # If you want to add more requirements, uncomment these 2 lines
    - echo "Installed everything!"
  artifacts:
    paths:
      - venv/

run_main:
  stage: run
  script:
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y
    - echo "Running main (with default - hardcoded settings)!"
    - python main.py
  dependencies:
    - build_project