image: "jjanzic/docker-python3-opencv"

stages:
  - build
  - run
  - test-percentage

build_project:
  stage: build
  script:
#    - pip install --upgrade pip
#    - pip install -r requirements.txt
    - echo "Installed everything!"