image: python:3.9

stages:
  - build
  - run
  - test-percentage

build_project:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Installed everything!"