image: "jjanzic/docker-python3-opencv"

stages:
  - build
  - run
  - test-percentage

build_project:
  stage: build
  script:
    - python -m venv venv
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y   # For opencv
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Installed everything!"
  artifacts:
    paths:
      - venv/

run_main:
  stage: run
  script:
    - source venv/bin/activate
    - apt-get update && apt-get install libgl1 -y
    - echo "Running main!"
    - python3 main.py --file_path ./dataset/pipeline/shorterVideo.avi --output_path ./Output.csv
  dependencies:
    - build_project
  artifacts:
    paths:
      - Output.csv